apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubec-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubec-app
  template:
    metadata:
      labels:
        app: kubec-app
    spec:
      containers:
      - name: kubec-app-container
        image: cre8tivity/kubec-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000